### ISSUE TITLE
Telegram Error 404 not found

### ISSUE THREAD

**Issue by kingofkillers91** [ChetanXpro/Telegram-Ai-Bot#2]
This is what i get when i run your script:

`──(root㉿kali)-[/home/alessandro/Scrivania/chatgpt-telegram-bot]
└─# npm start 

> telegrambot@1.0.0 start
> node index.js

/home/alessandro/Scrivania/chatgpt-telegram-bot/node_modules/telegraf/lib/core/network/client.js:293
            throw new error_1.default(data, { method, payload });
                  ^

TelegramError: 404: Not Found
    at Telegram.callApi (/home/alessandro/Scrivania/chatgpt-telegram-bot/node_modules/telegraf/lib/core/network/client.js:293:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Telegraf.launch (/home/alessandro/Scrivania/chatgpt-telegram-bot/node_modules/telegraf/lib/telegraf.js:182:78) {
  response: { ok: false, error_code: 404, description: 'Not Found' },
  on: { method: 'getMe', payload: {} }
}

Node.js v18.13.0
                                                                                                                    
┌──(root㉿kali)-[/home/alessandro/Scrivania/chatgpt-telegram-bot]
└─# 
`

I generated my own token thru botfather but and of course i pasted it in my .env file but it's not working. How does it work?
thanks

**Comment by kingofkillers91** [comment]
Bot token is correct "{"ok":true,"result":[]}"

**Comment by kingofkillers91** [comment]
The developer helped me solving it
